### PR TITLE
Check client->state != PC_ST_INITED before close TCP handle.

### LINKED ISSUE #56: Assertion failed in function uv_close() when cleanup a PC_ST_INITED client.
I'm test my [lua bindings for libpomelo2](https://github.com/xpol/lua-pomelo).
When I running unit test: create a client without connect, then I got

> Assertion failed: (0), function uv_close, file [src/unix/core.c, line 165](https://github.com/libuv/libuv/blob/v1.8.0/src/unix/core.c#L165).

*I linked with the latest libuv 1.8.0.*

### PR DESCRIPTION
**Pull request by xpol**
Fixes #56.

### CODE REVIEW

**Comment by cynron** [comment]
check tt->state == PC_ST_INITED ?

**Comment by xpol** [comment]
If it is always equivalent `tt->state == PC_ST_INITED` <=>  `tt->socket.type != UV_UNKNOWN_HANDLE`, then checking `tt->state == PC_ST_INITED` is better. UV_UNKNOWN_HANDLE is implementation details.
*Actually in my project I initially check the `tt->state`, I just not sure they are equivalent*

**Comment by cynron** [comment]
This issue occurs when calling `pc_client_cleanup` without `uv_tcp_init`  being called before. Furthermore, when `state == PC_ST_INITED`, the `tt->socket` is always closed or closing.
So it is ok to check `tt->state`.
You can update this pr and resend, thanks!

**Comment by xpol** [comment]
So we can just check `tt->state == PC_ST_INITED` without `!uv_is_closing((uv_handle_t*)&tt->socket)` ?

**Comment by xpol** [comment]
`tt->state == PC_ST_INITED || !uv_is_closing((uv_handle_t*)&tt->socket)` ?

**Comment by xpol** [comment]
oops
tt->state has the type of tr_uv_tcp_state_t:

```c
typedef enum {
    TR_UV_TCP_NOT_CONN,
    TR_UV_TCP_CONNECTING,
    TR_UV_TCP_HANDSHAKEING,
    TR_UV_TCP_DONE
} tr_uv_tcp_state_t;
```

And did you mean `TR_UV_TCP_NOT_CONN` <=> closed or closing.

If true, we should:

```c
    if (tt->state != TR_UV_TCP_NOT_CONN) {
        uv_close((uv_handle_t*)&tt->socket, NULL);
    }
```

**Comment by xpol** [comment]
There is another problem:

```c
void tcp__cleanup_async_cb(uv_async_t* a)
{
    GET_TT(a);

    assert(a == &tt->cleanup_async);

    tt->reset_fn(tt); // <-- this set tt->state to TR_UV_TCP_NOT_CONN and uv_close() if needed.

    if (tt->host) {
        pc_lib_free((char *)tt->host);
        tt->host = NULL;
    }

    tcp__cleanup_pc_json(&tt->handshake_opts);

    if (!uv_is_closing((uv_handle_t*)&tt->socket)) { // should not close again...
        uv_close((uv_handle_t*)&tt->socket, NULL);
    }
    tt->reconn_times = 0; 
// ....
}
```

**Comment by xpol** [comment]
I have reset the PR just do check in `tcp__reset`.

The duplicated close code in `tcp__cleanup_async_cb` will removed in another PR.

**Comment by xpol** [comment]
@cynron Is this OK to merge?

**Comment by cynron** [comment]
sorry, I am too busy these days, I will review the PR carefully later.

**Comment by cynron** [comment]
landed with line wrapping https://github.com/NetEase/libpomelo2/commit/4e3d5876194d5cb3bb984d56bb4f3534dfb17298

**Pull request closed without merging**
